### ISSUE TITLE
SEEGA failed in Slicer 4.11

### ISSUE THREAD

**Issue by windsto** [mnarizzano/SEEGA#32]
Dear Team:
 
SEEGA was failed in the new veision of Slicer 4.11.20200930

OS: WIN10 

![无标题](https://user-images.githubusercontent.com/73147907/96528787-1922f000-12b6-11eb-8c68-c4256f9546cd.png)

**Comment by BushraR** [comment]
Similar problem with macox for 4.11 release. It seems to be that the extension needs to be ported for python3


Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/busria/Downloads/SEEGA-master/BrainZoneDetector/BrainZoneDetector.py", line 52
    print self.lutPath
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.lutPath)?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/busria/Downloads/SEEGA-master/ContactPositionEstimator/ContactPositionEstimator.py", line 223
    self.electrodeList = sorted(self.electrodeList,key=lambda (x): x.name.text)
                                                              ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/busria/Downloads/SEEGA-master/Finalizer/Finalizer.py", line 184
    print "SPLITTING FIDUCIAL FILES"
                                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("SPLITTING FIDUCIAL FILES")?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/busria/Downloads/SEEGA-master/GMPIComputation/GMPIComputation.py", line 184
    print "RUN GMPI Computation"
                               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("RUN GMPI Computation")?

**Comment by BushraR** [comment]
Hello 
I have ported the Contact Position Estimator and Brain Zone Detector modules for Slicer 4.11  (for mac). I could add it to Pull request if allowed.

**Comment by hamandik** [comment]
I have just encountered same problem as windsto on Slicer 4.11.20200930. I can't foliow the thread to see what I need to do, are there a ported files I should be using?
![Screenshot 2021-03-07 at 21 06 40](https://user-images.githubusercontent.com/41474828/110254983-77145380-7f89-11eb-8f0f-b45a092e4549.png)

**Comment by BushraR** [comment]
Slicer 4.11 is based on newer version of Python, whereas current SEEGA is based on previous python version. I made small changes to fix python version mismatches and little bit of slicer updates in ContactPositionEstimator.py and BrainZoneDetector.py file. I could share the files if you are interested.

**Comment by hamandik** [comment]
thank you, yes please, that would be very helpful if you could share files for these.

**Comment by windsto** [comment]
That's great. Thanks for your sharing. How can we get these files?
On 3/8/2021 17:32，BushraR<notifications@github.com> wrote：

Slicer 4.11 is based on newer version of Python, whereas current SEEGA is based on previous python version. I made small changes to fix python version mismatches and little bit of slicer updates in ContactPositionEstimator.py and BrainZoneDetector.py file. I could share the files if you are interested.

**Comment by BushraR** [comment]
https://www.dropbox.com/sh/wlhml1r1uxjzmuc/AACtX1qyHSvHd8G6Ixxuwh-Xa?dl=0
Let me know if it works

**Comment by windsto** [comment]
Great, it's working well


Many times, the contacts are not in a straight line, just like the image in the attachment.
So I have a suggestion.
The position of the contact can be calculated directly from the spatial coordinates of the TIP and the SKULL ENTRY?
Don't rely on CT images and thresholds, just like another software, Brainstorm.The calculation process is also in the attachment.
| |
刘强强
|
|
windsto@163.com
|
签名由网易邮箱大师定制
On 3/10/2021 16:58，BushraR<notifications@github.com> wrote：

https://www.dropbox.com/sh/wlhml1r1uxjzmuc/AACtX1qyHSvHd8G6Ixxuwh-Xa?dl=0
Let me know if it works

**Comment by greydongilmore** [comment]
@mnarizzano is this repo still being maintained? It would be great to have the two open PRs looked at.. one fixes this Slicer version error and the other is a useful addition to store the electrode info in the description field of the markups list.

**Comment by MShabana90** [comment]
@mnarizzano @gabri470 This is a very interesting program. I am interested in learning how to use it. I am not sure if anyone has a tutorial of how to use the program. Currently an Epilepsy fellow and I am using Freesurfer for SEEG reconstructions however this seems like it would be a lot faster and easier to use. Not sure if anyone could help by posting a tutorial or video of how to use the program. 

Also of note, the finalizer and GMPIcomputation are still not loading for me in modules. Not sure if anyone has a fix for these.

**Comment by mosenco** [comment]
The update of SEEGA is now available and working for the newest Slicer 5.0.3
